[package]
name = "sequential"
version = "0.1.0"
edition = "2024"

[dependencies]
argh.workspace = true
bril-utils.workspace = true
utils.workspace = true
itertools.workspace = true
passes.workspace = true
simple_logger.workspace = true
log.workspace = true
